Removes un-used files
3sidedcube/ThunderBasics pull request #15
Opened 2018-02-06 15:37 UTC by simonmitchell

2018-02-08 09:18 UTC, MattCheetham requested changes
Looks good. Goodbye 7000 lines! Just document the new bits and we're good.

2018-02-08 09:18 UTC, MattCheetham commented on ThunderBasics/JSONSerialization+FromFile.swift
> +	open class func jsonObject(with resource: String?, extension fileExtension: String?, in bundle: Bundle = .main, options opt: JSONSerialization.ReadingOptions = []) throws -> Any {
Can you document this file please?

2018-02-08 09:18 UTC, MattCheetham commented on ThunderBasics/MapView+Fitting.swift
> +public extension MKMapView {
Please document this extension and methods

2018-02-08 09:44 UTC, simonmitchell commented
@MattCheetham documented! Tried to copy a lot of the documentation from similar methods on the Apple classes so they should be fairly explanatory 😊

2018-02-09 09:47 UTC, ryanbourneuk approved these changes

2018-02-12 15:23 UTC, merged